### ISSUE TITLE
New tag == new release ?

### ISSUE THREAD

**Issue by iskunk** [chromium-linux-tarballs/chromium-tarballs#10]
Currently, on this repo's front page, under "Releases" it says "7 tags." This implies that each tag equates to a release.

Using the "Watch" widget, I've subscribed to notifications for this repo, specifically via "Custom -> [x] Releases." I want to get an e-mail each time a new tarball comes out, which equals a new tag, which should equal a new release. But that does not appear to be happening, or at least it didn't for 133.0.6847.2.

I think an explicit step may be needed (beyond just pushing a tag) to cut a new release. Here is a workflow that does exactly that: https://github.com/ungoogled-software/ungoogled-chromium/blob/master/.github/workflows/release-on-tag.yml

(The GitHub Action used there is unmaintained, however. The alternative would be to use `gh release create`.)

I'd suggest doing releases only for new stable versions, as I think the interest in packaging beta or dev releases would be much more limited. (It does appear that GitHub releases have a "prerelease" flag, but I'm not sure what aspects of the resulting behavior are different.)

**Comment by Kangie** [comment]
This looks like it would trivially do the job, but we'd have to trigger on all tags.

https://github.com/comnoco/create-release-action

We could prefix the channel to the tags, maybe, but I'm not sure I like that. Maybe we can adapt it to trigger within the tag workflow, like the various IRC channel notifs?

https://github.com/chromium-linux-tarballs/chromium-tarballs/blob/fa02f8cd771dcaaad9b4dc6f06ed4ab4041e779a/.github/workflows/cron.yml#L60-L68

Something like

```yml
      - name: Create Release
        id: create_release
        if: steps.tag_versions.outputs.stable != ''
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_versions.outputs.stable_tag }} # We will need to export the tag but that's fine
          release_name: Release ${{ steps.tag_versions.outputs.stable }}
          body: |
          New ${{ steps.tag_versions.outputs.stable }}
          draft: false
          prerelease: false 
```

We could repeat that for dev/beta as prerelease tags.
